version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

formats:
  - epub

python:
  install:
    - requirements: next_docs/zh_cn/requirements.txt

sphinx:
  configuration: next_docs/zh_cn/conf.py
